services:
  backend:
    build: ./backend
    container_name: FactoExpense-backend
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_HOST=db
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: FactoExpense-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0

  db:
    image: mysql:8
    container_name: MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: